### ISSUE TITLE
Nucleotide position error

### ISSUE THREAD

**Issue by dankein** [philipwfowler/genucator#1]
Hi,
I'm looking for the positions of the mutations from the new CRyPTIC paper and it seems like there's an error in the numbering for rpoB, embB, embA, fabG1 and inhA - the nt position given is one position too low but they are the correct nt letter.

Both katG and pncA appear correct.

**Comment by philipwfowler** [comment]
Fixed in `gumpy`. gemucator is now DEPRECATED.
