### ISSUE TITLE
Wrong default path to genbank file

### ISSUE THREAD

**Issue by flashton2003** [philipwfowler/genucator#2]
We are using genmucator but the default path to the genbank file is incorrect.

It specifies:

`/home/ubuntu/.local/lib/python3.5/site-packages/gemucator-1.0.1-py3.5.egg/gemucator/../config/H37rV.gbk`

when the file is actually (Rv is switched for rV)

`/home/ubuntu/.local/lib/python3.5/site-packages/gemucator-1.0.1-py3.5.egg/gemucator/../config/H37Rv.gbk`

**Comment by philipwfowler** [comment]
Fixed in `gumpy`. gemucator is now DEPRECATED.
